INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Nothing","vague",20,"2020-12-30","2100-12-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Book","book",500,"2018-09-10","2019-09-09");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Make something","vague",1500,"2018-05-01","2018-05-11");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Five Books","book",2500,"2018-09-10","2023-10-26");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Desert Island","weird",100000,"2030-10-20","2031-10-10");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("200 sheets of fine paper","book",100,"2018-7-29","2018-9-17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("draw pictures","book",50,"2074-01-03","2074-01-04");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("press flowers","cute",20,"2038-7-23","2038-07-30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("knitting patterns","cute",40,"2020-12-20","2021-04-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("gather favorite quotes","book",10,"2022-08-08","2023-05-17");
INSERT INTO users (name, age) VALUES ("King",7);
INSERT INTO users (name, age) VALUES ("Charles",18);
INSERT INTO users (name, age) VALUES ("English",21);
INSERT INTO users (name, age) VALUES ("Eric",28);
INSERT INTO users (name, age) VALUES ("Board",38);
INSERT INTO users (name, age) VALUES ("East",12);
INSERT INTO users (name, age) VALUES ("Kissena",12);
INSERT INTO users (name, age) VALUES ("January",21);
INSERT INTO users (name, age) VALUES ("Charles",60);
INSERT INTO users (name, age) VALUES ("White",100);
INSERT INTO users (name, age) VALUES ("Patrick",22);
INSERT INTO users (name, age) VALUES ("Bill",71);
INSERT INTO users (name, age) VALUES ("Martin",84);
INSERT INTO users (name, age) VALUES ("Edward",63);
INSERT INTO users (name, age) VALUES ("Dahlberg",52);
INSERT INTO users (name, age) VALUES ("Aram",41);
INSERT INTO users (name, age) VALUES ("George",41);
INSERT INTO users (name, age) VALUES ("Bernard",61);
INSERT INTO users (name, age) VALUES ("Shaw",113);
INSERT INTO users (name, age) VALUES ("Byron",55);
INSERT INTO pledges (amount, project_id, user_id) VALUES (15,15,7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (14,6,4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (12,18,10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1,7,9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (186,12,8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (11,18,7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (159,20,5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (17,10,5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (36,7,10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (20,17,1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (158,11,2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (517,19,9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (198,16,5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (19,9,10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2,2,5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (165,11,2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (919,15,4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (18,12,9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13,13,2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (104,20,4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (63,9,3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (16,16,5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (91,1,2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (122,19,20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (18,19,9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (178,6,1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (18,12,8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (11,12,1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (64,9,4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (179,2,7);
